In [ ]:
import numpy as np

matrix = np.array([[0, 0, 0, 1],
                   [0, 10, 0, -1],
                   [0, 0, 1, 0]])

direction = [(-1, 0), (1, 0), (0, -1), (0, 1)]

gamma = 0.9
iterations = 6

rows, cols = matrix.shape

infinity = float('inf')
new_matrix = np.where(matrix == 10, infinity, matrix).astype(float)

print("Initial Value Function:")
print(new_matrix, "\n")

for it in range(iterations):
    temp_matrix = new_matrix.copy()

    for row in range(rows):
        for col in range(cols):
            if matrix[row, col] in {1, -1} or new_matrix[row, col] == infinity:
                continue

            values = [new_matrix[new_row, new_col] for dr, dc in direction
                      if 0 <= (new_row := row + dr) < rows
                      and 0 <= (new_col := col + dc) < cols
                      and new_matrix[new_row, new_col] != infinity]

            if values:
                temp_matrix[row, col] = matrix[row, col] + gamma * max(values)

    new_matrix = temp_matrix

    print(f"Iteration {it + 1}:")
    print(new_matrix, "\n")


Initial Value Function:
[[ 0.  0.  0.  1.]
 [ 0. inf  0. -1.]
 [ 0.  0.  1.  0.]] 

Iteration 1:
[[ 0.   0.   0.9  1. ]
 [ 0.   inf  0.9 -1. ]
 [ 0.   0.9  1.   0.9]] 

Iteration 2:
[[ 0.    0.81  0.9   1.  ]
 [ 0.     inf  0.9  -1.  ]
 [ 0.81  0.9   1.    0.9 ]] 

Iteration 3:
[[ 0.729  0.81   0.9    1.   ]
 [ 0.729    inf  0.9   -1.   ]
 [ 0.81   0.9    1.     0.9  ]] 

Iteration 4:
[[ 0.729  0.81   0.9    1.   ]
 [ 0.729    inf  0.9   -1.   ]
 [ 0.81   0.9    1.     0.9  ]] 

Iteration 5:
[[ 0.729  0.81   0.9    1.   ]
 [ 0.729    inf  0.9   -1.   ]
 [ 0.81   0.9    1.     0.9  ]] 

Iteration 6:
[[ 0.729  0.81   0.9    1.   ]
 [ 0.729    inf  0.9   -1.   ]
 [ 0.81   0.9    1.     0.9  ]] 



In [ ]:
import numpy as np

# Define a reward matrix
reward_matrix = [[0, 0, 0, 1], [0, 0, 0, -1], [0, 0, 0, 0], [0, 0, 0, 0]]

# Direction offsets (up, down, left, right)
directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]

# Set gamma for discounting future rewards
gamma = 0.9
num_iterations = 5

# Get the dimensions of the matrix
rows, cols = reward_matrix.shape

# Representing infinity for unreachable positions
infinity_value = float('inf')
modified_matrix = np.where(reward_matrix == 10, infinity_value, reward_matrix).astype(float)

# Display the initial value function
print("Initial Value Function:")
print(modified_matrix, "\n")

# Run value iteration for the specified number of iterations
for iteration in range(num_iterations):
    temp_values = modified_matrix.copy()

    for i in range(rows):
        for j in range(cols):
            # Skip processing if it's a terminal state or already infinity
            if reward_matrix[i, j] in {1, -1} or modified_matrix[i, j] == infinity_value:
                continue

            # List to store the possible values for neighboring states
            neighboring_values = []
            for di, dj in directions:
                # Calculate the new row and column based on direction
                new_i, new_j = i + di, j + dj
                if 0 <= new_i < rows and 0 <= new_j < cols and modified_matrix[new_i, new_j] != infinity_value:
                    neighboring_values.append(modified_matrix[new_i, new_j])

            # If valid neighboring states exist, update the value
            if neighboring_values:
                temp_values[i, j] = reward_matrix[i, j] + gamma * max(neighboring_values)

    # Update the matrix for the next iteration
    modified_matrix = temp_values

    # Print the value function after this iteration
    print(f"After Iteration {iteration + 1}:")
    print(modified_matrix, "\n")


Initial Value Function:
[[ 0.  0.  0.  1.]
 [ 0. inf  0. -1.]
 [ 0.  0.  1.  0.]] 

After Iteration 1:
[[ 0.   0.   0.9  1. ]
 [ 0.   inf  0.9 -1. ]
 [ 0.   0.9  1.   0.9]] 

After Iteration 2:
[[ 0.    0.81  0.9   1.  ]
 [ 0.     inf  0.9  -1.  ]
 [ 0.81  0.9   1.    0.9 ]] 

After Iteration 3:
[[ 0.729  0.81   0.9    1.   ]
 [ 0.729    inf  0.9   -1.   ]
 [ 0.81   0.9    1.     0.9  ]] 

After Iteration 4:
[[ 0.729  0.81   0.9    1.   ]
 [ 0.729    inf  0.9   -1.   ]
 [ 0.81   0.9    1.     0.9  ]] 

After Iteration 5:
[[ 0.729  0.81   0.9    1.   ]
 [ 0.729    inf  0.9   -1.   ]
 [ 0.81   0.9    1.     0.9  ]] 

After Iteration 6:
[[ 0.729  0.81   0.9    1.   ]
 [ 0.729    inf  0.9   -1.   ]
 [ 0.81   0.9    1.     0.9  ]] 



In [ ]:
import numpy as np

# Given matrix and parameters
matrix = np.array([[0, 0, 0, 1],
                   [0, 10, 0, -1],
                   [0, 0, 1, 0]])

directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]
gamma = 0.9
iterations = 6
step_reward = -0.04  # Small negative reward for each step

# Initialize value function with zeros
value_function = np.zeros(matrix.shape)

# Value Iteration
for it in range(iterations):
    new_value_function = np.copy(value_function)
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            # Skip terminal states, retain their values
            if matrix[i][j] == 1 or matrix[i][j] == -1:
                new_value_function[i][j] = matrix[i][j]
                continue

            # Calculate value for each action
            values = []
            for d in directions:
                next_i, next_j = i + d[0], j + d[1]

                # Check bounds and calculate the next state value
                if 0 <= next_i < matrix.shape[0] and 0 <= next_j < matrix.shape[1]:
                    next_value = value_function[next_i][next_j]
                else:
                    next_value = value_function[i][j]  # If out of bounds, stay in place

                # Apply the Bellman update equation
                value = step_reward + gamma * next_value
                values.append(value)

            # Update value function with the maximum value from all actions
            new_value_function[i][j] = max(values)

    value_function = new_value_function
    print(f"Iteration {it+1}:\n{value_function}\n")


Iteration 1:
[[-0.04 -0.04 -0.04  1.  ]
 [-0.04 -0.04 -0.04 -1.  ]
 [-0.04 -0.04  1.   -0.04]]

Iteration 2:
[[-0.076 -0.076  0.86   1.   ]
 [-0.076 -0.076  0.86  -1.   ]
 [-0.076  0.86   1.     0.86 ]]

Iteration 3:
[[-0.1084  0.734   0.86    1.    ]
 [-0.1084  0.734   0.86   -1.    ]
 [ 0.734   0.86    1.      0.86  ]]

Iteration 4:
[[ 0.6206  0.734   0.86    1.    ]
 [ 0.6206  0.734   0.86   -1.    ]
 [ 0.734   0.86    1.      0.86  ]]

Iteration 5:
[[ 0.6206  0.734   0.86    1.    ]
 [ 0.6206  0.734   0.86   -1.    ]
 [ 0.734   0.86    1.      0.86  ]]

Iteration 6:
[[ 0.6206  0.734   0.86    1.    ]
 [ 0.6206  0.734   0.86   -1.    ]
 [ 0.734   0.86    1.      0.86  ]]



In [ ]:
import numpy as np

grid = np.array([[0, 0, 0, 1],
                 [0, 2, 0, -1],
                 [0, 0, 1, 0]])


# States: All grid cells
states = [(i, j) for i in range(grid.shape[0]) for j in range(grid.shape[1])]

actions = ['up', 'down', 'left', 'right']
directions = {
    'up': (-1, 0),
    'down': (1, 0),
    'left': (0, -1),
    'right': (0, 1)
}


gamma = 0.9 # discount factor
step_reward = -1  # penalty for each step
iterations = 6


def transition_model(state, action, next_state):
    i, j = state
    ni, nj = next_state
    if (ni, nj) == (i + directions[action][0], j + directions[action][1]):
        # Check bounds
        if 0 <= ni < grid.shape[0] and 0 <= nj < grid.shape[1]:
            return 1.0
    if (ni, nj) == (i, j):  # If out of bounds, stay in place
        return 1.0
    return 0.0

# Reward function
def reward_function(state, action, next_state):
    ni, nj = next_state
    if grid[ni][nj] == 1 or grid[ni][nj] == -1:
        return grid[ni][nj]  # Terminal state reward
    else:
        return step_reward  # Step penalty

# Value Iteration for 6 iterations
def value_iteration_6(states, actions, transition_model, reward_function, gamma, iterations):
    # Initialize value function
    V = {s: 0 for s in states}

    for it in range(iterations):
        new_V = V.copy()
        for s in states:
            # Skip terminal states
            if grid[s[0]][s[1]] in [1, -1]:
                new_V[s] = grid[s[0]][s[1]]
                continue

            # Bellman update
            new_V[s] = max(sum(transition_model(s, a, s_next) *
                               (reward_function(s, a, s_next) + gamma * V[s_next])
                               for s_next in states) for a in actions)

        # Update value function
        V = new_V

        # Display value function after each iteration
        print(f"\nValue Function after iteration {it+1}:")
        for i in range(grid.shape[0]):
            row = ""
            for j in range(grid.shape[1]):
                row += f"{V[(i, j)]:>8.2f} "
            print(row)

# Run value iteration for 6 iterations
value_iteration_6(states, actions, transition_model, reward_function, gamma, iterations)



Value Function after iteration 1:
   -1.00    -1.00     0.00     1.00 
   -1.00    -2.00     0.00    -1.00 
   -1.00     0.00     1.00     0.00 

Value Function after iteration 2:
   -1.90    -1.90     0.90     1.00 
   -1.90    -3.80     0.90    -1.00 
   -1.90     0.90     1.00     0.90 

Value Function after iteration 3:
   -2.71    -2.71     1.71     1.00 
   -2.71    -4.61     1.71    -1.00 
   -2.71     1.71     1.00     1.71 

Value Function after iteration 4:
   -3.44    -2.90     2.44     1.00 
   -3.44    -4.61     2.44    -1.00 
   -2.90     2.44     1.00     2.44 

Value Function after iteration 5:
   -4.10    -2.41     3.10     1.00 
   -4.10    -3.95     3.10    -1.00 
   -2.41     3.10     1.00     3.10 

Value Function after iteration 6:
   -4.69    -1.39     3.69     1.00 
   -4.69    -2.77     3.69    -1.00 
   -1.39     3.69     1.00     3.69 


In [ ]:
# main code -
import numpy as np

grid = np.array([[0, 0, 0, 1],
                 [0, 2, 0, -1],
                 [0, 0, 1, 0]])

# 1: Positive terminal state (reward +1)
# -1: Negative terminal state (reward -1)
# 2: Wall

states = [(i, j) for i in range(grid.shape[0]) for j in range(grid.shape[1])]

# Actions: Moving up, down, left, or right
actions = ['up', 'down', 'left', 'right']
directions = {
    'up': (-1, 0),
    'down': (1, 0),
    'left': (0, -1),
    'right': (0, 1)
}


gamma = 0.99 # discount factor
step_reward = -1 # penalty
iterations = 6

# Initialize Value Function with walls as infinity
infinity = float('inf')
value_matrix = np.where(grid == 2, infinity, grid).astype(float)

print("Initial Value Function:")
print(value_matrix, "\n")

def transition_model(state, action, next_state):
    i, j = state
    ni, nj = next_state

    # checks if the potential next state (ni, nj) is indeed the state you would end up in by moving from (i, j) according to the specified action.
    # If this condition is true it means the action leads directly to the next state (ni, nj)

    if (ni, nj) == (i + directions[action][0], j + directions[action][1]):

        # Check bounds
        if 0 <= ni < grid.shape[0] and 0 <= nj < grid.shape[1]:
            # Check for wall, if wall then stay in current state
            if grid[ni][nj] == 2:
                return 1.0
            if (ni, nj) == (i, j)
            else 0.0
            return 1.0

    # If out of bounds or wall, stay in place
    if (ni, nj) == (i, j):
        return 1.0
    return 0.0

def reward_function(state, action, next_state):
    ni, nj = next_state
    if grid[ni][nj] == 1 or grid[ni][nj] == -1:
        return grid[ni][nj]  # Terminal state reward
    else:
        return step_reward

def value_iteration_6(states, actions, transition_model, reward_function, gamma, iterations):
    V = {s: 0 for s in states}

    for it in range(iterations):
        new_V = V.copy()
        for s in states:
            # Skip terminal states and walls
            if grid[s[0]][s[1]] in [1, -1] or grid[s[0]][s[1]] == 2:
                new_V[s] = grid[s[0]][s[1]]
                continue

            # Bellman used here
            new_V[s] = max(sum(transition_model(s, a, s_next) * (reward_function(s, a, s_next) + gamma * V[s_next])
                               for s_next in states) for a in actions)

        # Update value function
        V = new_V

        # Display value function after each iteration
        print(f"\nValue Function after iteration {it+1}:")
        for i in range(grid.shape[0]):
            row = ""
            for j in range(grid.shape[1]):
                if grid[i][j] == 2:
                    row += "  Wall   "
                else:
                    row += f"{V[(i, j)]:>8.2f} "
            print(row)

value_iteration_6(states, actions, transition_model, reward_function, gamma, iterations)


Initial Value Function:
[[ 0.  0.  0.  1.]
 [ 0. inf  0. -1.]
 [ 0.  0.  1.  0.]] 


Value Function after iteration 1:
   -1.00    -1.00     0.00     1.00 
   -1.00   Wall       0.00    -1.00 
   -1.00     0.00     1.00     0.00 

Value Function after iteration 2:
   -1.99    -1.99     0.99     1.00 
   -1.99   Wall       0.99    -1.00 
   -1.99     0.99     1.00     0.99 

Value Function after iteration 3:
   -2.97    -2.97     1.97     1.00 
   -2.97   Wall       1.97    -1.00 
   -2.97     1.97     1.00     1.97 

Value Function after iteration 4:
   -3.94    -2.99     2.94     1.00 
   -3.94   Wall       2.94    -1.00 
   -2.99     2.94     1.00     2.94 

Value Function after iteration 5:
   -4.90    -2.05     3.90     1.00 
   -4.90   Wall       3.90    -1.00 
   -2.05     3.90     1.00     3.90 

Value Function after iteration 6:
   -5.85    -0.17     5.72     1.00 
   -5.85   Wall       5.72    -1.00 
   -0.17     4.85     1.00     4.85 


In [ ]:
# main code policy iteration
import numpy as np
import random

# Gridworld setup
matrix = np.array([[0, 0, 0, 1],
                   [0, 10, 0, -1],
                   [0, 0, 1, 0]])

direction = {
    'up': (-1, 0),
    'down': (1, 0),
    'left': (0, -1),
    'right': (0, 1)
}
actions = list(direction.keys())

gamma = 0.9
theta = 1e-4
rows, cols = matrix.shape
infinity = float('inf')
value_matrix = np.where(matrix == 10, infinity, matrix).astype(float)

policy = {}
for row in range(rows):
    for col in range(cols):
        if matrix[row, col] not in {1, -1} and matrix[row, col] != 10:
            policy[(row, col)] = random.choice(actions)

print("Initial Policy:")
for r in range(rows):
    row = ""
    for c in range(cols):
        if (r, c) in policy:
            row += f"{policy[(r, c)]:>7} "
        elif matrix[r, c] == 10:
            row += "  Wall   "
        else:
            row += "Terminal "
    print(row)
print()

def get_next_state_and_reward(state, action):
    r, c = state
    dr, dc = direction[action]
    new_r, new_c = r + dr, c + dc

    # Check bounds
    if 0 <= new_r < rows and 0 <= new_c < cols:
        # Check wall
        if matrix[new_r, new_c] == 10:
            return (r, c), -1  # Stay in place
        return (new_r, new_c), matrix[new_r, new_c]
    return (r, c), -1  # Out of bounds, stay in place

def policy_evaluation(policy, value_matrix, gamma, theta):
    while True:
        delta = 0
        for r in range(rows):
            for c in range(cols):
                state = (r, c)

                if matrix[r, c] in {1, -1} or matrix[r, c] == 10:
                    continue  # Skip terminal states and walls

                v = value_matrix[r, c]
                action = policy[state]

                # Get next state and reward
                next_state, reward = get_next_state_and_reward(state, action)
                value_matrix[r, c] = reward + gamma * value_matrix[next_state]

                delta = max(delta, abs(v - value_matrix[r, c]))

        # Check for convergence
        if delta < theta:
            break

def policy_improvement(policy, value_matrix, gamma):
    policy_stable = True

    for r in range(rows):
        for c in range(cols):
            state = (r, c)

            if matrix[r, c] in {1, -1} or matrix[r, c] == 10:
                continue  # Skip terminal states and walls

            old_action = policy[state]

            # Calculate value for all actions
            action_values = {}
            for action in actions:
                next_state, reward = get_next_state_and_reward(state, action)
                action_values[action] = reward + gamma * value_matrix[next_state]

            # action with the highest value
            best_action = max(action_values, key=action_values.get)
            policy[state] = best_action

            if old_action != best_action:
                policy_stable = False

    return policy_stable

def policy_iteration(policy, value_matrix, gamma, theta):
    iteration = 0
    while True:
        iteration += 1
        print(f"\nPolicy Iteration {iteration}: Policy Evaluation")
        policy_evaluation(policy, value_matrix, gamma, theta)

        print("\nValue Function:")
        for i in range(rows):
            row = ""
            for j in range(cols):
                if matrix[i][j] == 10:
                    row += "  Wall   "
                else:
                    row += f"{value_matrix[i][j]:>8.2f} "
            print(row)

        print("\nPolicy:")
        for i in range(rows):
            row = ""
            for j in range(cols):
                if (i, j) in policy:
                    row += f"{policy[(i, j)]:>8} "
                elif matrix[i][j] == 10:
                    row += "  Wall   "
                else:
                    row += "Terminal "
            print(row)

        print("\nPolicy Improvement")
        policy_stable = policy_improvement(policy, value_matrix, gamma)

        if policy_stable:
            print("\nPolicy Converged!")
            break

policy_iteration(policy, value_matrix, gamma, theta)


Initial Policy:
     up      up    left Terminal 
     up   Wall        up Terminal 
   left      up Terminal      up 


Policy Iteration 1: Policy Evaluation

Value Function:
  -10.00   -10.00    -9.00     1.00 
   -9.00   Wall      -8.10    -1.00 
  -10.00   -10.00     1.00    -1.90 

Policy:
      up       up     left Terminal 
      up   Wall         up Terminal 
    left       up Terminal       up 

Policy Improvement

Policy Iteration 2: Policy Evaluation

Value Function:
   -0.00     1.71     1.90     1.00 
   -0.00   Wall       1.90    -1.00 
   -0.00     1.90     1.00     1.90 

Policy:
    down    right    right Terminal 
      up   Wall       down Terminal 
      up    right Terminal     left 

Policy Improvement

Policy Iteration 3: Policy Evaluation

Value Function:
    1.54     1.71     1.90     1.00 
    1.54   Wall       1.90    -1.00 
    1.71     1.90     1.00     1.90 

Policy:
   right    right    right Terminal 
    down   Wall       down Terminal 
   right    righ

In [ ]:
import numpy as np

# 2 = Wall, 1 = Goal, 0 = Open Space
maze = np.array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
                 [2, 0, 2, 0, 0, 0, 2, 0, 2, 2],
                 [2, 0, 2, 0, 2, 2, 2, 0, 1, 2],
                 [2, 0, 2, 0, 0, 2, 2, 2, 2, 2],
                 [2, 0, 2, 2, 0, 2, 0, 0, 0, 2],
                 [2, 0, 0, 0, 0, 2, 2, 0, 2, 2],
                 [2, 2, 0, 2, 2, 0, 2, 0, 2, 2],
                 [2, 2, 0, 0, 0, 0, 2, 0, 2, 2],
                 [2, 2, 2, 2, 2, 0, 0, 0, 2, 2],
                 [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

states = [(i, j) for i in range(maze.shape[0]) for j in range(maze.shape[1])]
actions = ['up', 'down', 'left', 'right']
directions = {
    'up': (-1, 0),
    'down': (1, 0),
    'left': (0, -1),
    'right': (0, 1)
}

gamma = 0.99
step_reward = -1
iterations = 6

infinity = float('inf')
value_matrix = np.where(maze == 2, infinity, maze).astype(float)

print("Initial Value Function:")
print(value_matrix, "\n")

def transition_model(state, action, next_state):
    i, j = state
    ni, nj = next_state

    if (ni, nj) == (i + directions[action][0], j + directions[action][1]):
        if 0 <= ni < maze.shape[0] and 0 <= nj < maze.shape[1]:
            if maze[ni][nj] == 2:
                return 1.0 if (ni, nj) == (i, j) else 0.0
            return 1.0

    if (ni, nj) == (i, j):
        return 1.0
    return 0.0

def reward_function(state, action, next_state):
    ni, nj = next_state
    if maze[ni][nj] == 1:
        return 1
    else:
        return step_reward

def value_iteration(states, actions, transition_model, reward_function, gamma, iterations):
    V = {s: 0 for s in states}

    for it in range(iterations):
        new_V = V.copy()
        for s in states:
            if maze[s[0]][s[1]] == 1 or maze[s[0]][s[1]] == 2:
                new_V[s] = maze[s[0]][s[1]]
                continue

            new_V[s] = max(sum(transition_model(s, a, s_next) *
                               (reward_function(s, a, s_next) + gamma * V[s_next])
                               for s_next in states) for a in actions)

        V = new_V

        print(f"\nValue Function after iteration {it+1}:")
        for i in range(maze.shape[0]):
            row = ""
            for j in range(maze.shape[1]):
                if maze[i][j] == 2:
                    row += "  Wall   "
                elif maze[i][j] == 1:
                    row += "  Goal   "
                else:
                    row += f"{V[(i, j)]:>8.2f} "
            print(row)

value_iteration(states, actions, transition_model, reward_function, gamma, iterations)


Initial Value Function:
[[inf inf inf inf inf inf inf inf inf inf]
 [inf  0. inf  0.  0.  0. inf  0. inf inf]
 [inf  0. inf  0. inf inf inf  0.  1. inf]
 [inf  0. inf  0.  0. inf inf inf inf inf]
 [inf  0. inf inf  0. inf  0.  0.  0. inf]
 [inf  0.  0.  0.  0. inf inf  0. inf inf]
 [inf inf  0. inf inf  0. inf  0. inf inf]
 [inf inf  0.  0.  0.  0. inf  0. inf inf]
 [inf inf inf inf inf  0.  0.  0. inf inf]
 [inf inf inf inf inf inf inf inf inf inf]] 


Value Function after iteration 1:
  Wall     Wall     Wall     Wall     Wall     Wall     Wall     Wall     Wall     Wall   
  Wall      -1.00   Wall      -1.00    -1.00    -1.00   Wall      -1.00   Wall     Wall   
  Wall      -1.00   Wall      -1.00   Wall     Wall     Wall       0.00   Goal     Wall   
  Wall      -1.00   Wall      -1.00    -1.00   Wall     Wall     Wall     Wall     Wall   
  Wall      -1.00   Wall     Wall      -1.00   Wall      -1.00    -1.00    -1.00   Wall   
  Wall      -1.00    -1.00    -1.00    -1.00   Wall  